version: "3.0"
services: 
  frontend:
    image: "vladene/vampire-frontend:${VAMPIRE_VERSION}"
    ports: 
    - "3000:80"
    depends_on:
    - backend
    deploy:
      restart_policy:
        condition: on-failure
  backend:
    image: "vladene/vampire-backend:${VAMPIRE_VERSION}"
    ports:
    - "8000:8080"
    volumes: 
      - type: bind
        source: ~/vampire-online/uploaded_problems
        target: /app/uploaded_problems
      - type: bind
        source: ~/vampire-online/tutorial
        targe: /app/tutorial
      - type: bind
        source: ~/vampire-online/problem_library
        target: /app/problem_library
    deploy:
      restart_policy:
        condition: on-failure